version: "3.8"
services:
  backend-api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile-backend-api
    ports:
    - "8081:8081"
  backend-api-2:
    container_name: backend-api-2
    build:
      context: .
      dockerfile: Dockerfile-backend-api
    ports:
      - "8082:8081"
  backend-api-3:
    container_name: backend-api-3
    build:
      context: .
      dockerfile: Dockerfile-backend-api
    ports:
      - "8083:8081"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
  centraldogma:
    image: line/centraldogma
    ports:
      - 36462:36462
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
