FROM gradle:7.2.0-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src/backend-api
RUN gradle build --no-daemon -x test

FROM adoptopenjdk/openjdk11:jre-11.0.12_7-alpine
EXPOSE 8080
RUN mkdir /app
COPY --from=build /home/gradle/src/backend-api/build/libs/app.jar /app/app.jar
ENTRYPOINT ["java","-Xms2g", "-Xmx4g", "-jar","/app/app.jar"]
