version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
  centraldogma:
    image: line/centraldogma
    ports:
      - 36462:36462
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
