global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
  - job_name: 'backend-api'
    scrape_interval: 5s
    metrics_path: '/internal/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'backend-api-2'
    scrape_interval: 5s
    metrics_path: '/internal/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'backend-api-3'
    scrape_interval: 5s
    metrics_path: '/internal/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'frontend-web'
    scrape_interval: 5s
    metrics_path: '/internal/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
